/* Only for mysql */

DROP DATABASE IF EXISTS Homework_1;

CREATE DATABASE Homework_1;
USE Homework_1;

/* Only for mysql */

CREATE TABLE Tournament (
	TOURNEY_ID  VARCHAR(255) PRIMARY KEY,
	TOURNEY_NAME VARCHAR(255),
	SURFACE VARCHAR(255),
	DRAW_SIZE INT,
	TOURNEY_LEVEL VARCHAR(2),
	TOURNEY_DATE DATE
);

CREATE TABLE Player (
	ID INT PRIMARY KEY,
	NAME VARCHAR(255),
	HAND CHAR,
	HT INT,
	IOC VARCHAR(3),
	DOB DATE,
	AGE()
);

CREATE TABLE Match (
	MATCH_ID INT AUTOINCREMENT PRIMARY KEY,
	ROUND VARCHAR(255),
	MINUTES INT,
	MATCH_NUM INT,
	BEST_OF INT,
	SCORE VARCHAR(255),
	NUM_SETS INT,
	FOREIGN KEY (TOURNEY_ID) REFERENCES Tournament(TOURNEY_ID)
);

CREATE TABLE Player_Match (
	PLAYER_ID FOREIGN KEY REFERENCES Player,
	MATCH_ID FOREIGN KEY REFERENCES Match,
	PRIMARY KEY (PLAYER_ID, MATCH_ID),
	IS_WINNER BOOLEAN,
	RANK_BEFORE INT,
	RANKING_POINTS INT,
	ACES INT,
	DFS INT,
	SVPTS INT,
	1ST_IN INT,
	1ST_WON INT,
	2ND_WON INT,
	SV_GMS INT,
	BP_SAVED INT,
	BP_FACED INT
);

CREATE TABLE Player_Tourney (
	FOREIGN KEY (PLAYER_ID) REFERENCES Player(ID),
	FOREIGN KEY (MATCH_ID)  REFERENCES Match(MATCH_ID)
	SEED INT,
	ENTRY VARCHAR(10)
);
